export const data = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1972115/pexels-photo-1972115.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Long Sleeve Graphic T-shirt",
    desc: "Long Sleeve Graphic T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt T-shirt",
    isNew: true,
    oldPrice: 19,
    price: 12,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1759622/pexels-photo-1759622.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Coat",
    desc: "Coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat This is a coat",
    isNew: true,
    oldPrice: 19,
    price: 12,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1457983/pexels-photo-1457983.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Skirt",
    desc: "Skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt This is a skirt",
    oldPrice: 19,
    price: 12,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/2065200/pexels-photo-2065200.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Sport shoe",
    desc: "Sport shoe",
    oldPrice: 19,
    price: 12,
  },
];
